/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder16_26 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] alufn,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  reg [15:0] xb;
  
  reg [15:0] mp;
  
  reg [15:0] div;
  
  always @* begin
    
    case (alufn[0+0-:1])
      1'h1: begin
        sum = a - b;
        xb = -b;
      end
      default: begin
        sum = a + b;
        xb = b;
      end
    endcase
    v = (a[15+0-:1] & xb[15+0-:1] & ~sum[15+0-:1]) + (~a[15+0-:1] & ~xb[15+0-:1] & sum[15+0-:1]);
    z = ~((|sum));
    n = sum[15+0-:1];
    mp = a * b;
    div = a / b;
    
    case ({alufn[2+0-:1], alufn[1+0-:1]})
      2'h1: begin
        out = mp;
      end
      2'h2: begin
        out = div;
      end
      default: begin
        out = sum;
      end
    endcase
  end
endmodule
