/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_2 (
    input clk,
    input rst,
    input [15:0] score,
    output reg [13:0] seg
  );
  
  
  
  always @* begin
    
    case (score)
      16'h0000: begin
        seg = 14'h0081;
      end
      16'h0001: begin
        seg = 14'h00cf;
      end
      16'h0002: begin
        seg = 14'h0092;
      end
      16'h0003: begin
        seg = 14'h0086;
      end
      16'h0004: begin
        seg = 14'h00cc;
      end
      16'h0005: begin
        seg = 14'h00a4;
      end
      16'h0006: begin
        seg = 14'h00a0;
      end
      16'h0007: begin
        seg = 14'h008f;
      end
      16'h0008: begin
        seg = 14'h0080;
      end
      16'h0009: begin
        seg = 14'h0084;
      end
      16'h000a: begin
        seg = 14'h2781;
      end
      16'h000b: begin
        seg = 14'h27cf;
      end
      16'h000c: begin
        seg = 14'h2792;
      end
      16'h000d: begin
        seg = 14'h2786;
      end
      16'h000e: begin
        seg = 14'h27cc;
      end
      16'h000f: begin
        seg = 14'h27a4;
      end
      16'h0010: begin
        seg = 14'h27a0;
      end
      16'h0011: begin
        seg = 14'h278f;
      end
      16'h0012: begin
        seg = 14'h2780;
      end
      16'h0013: begin
        seg = 14'h2784;
      end
      16'h0014: begin
        seg = 14'h0901;
      end
      16'h0015: begin
        seg = 14'h094f;
      end
      16'h0016: begin
        seg = 14'h0912;
      end
      16'h0017: begin
        seg = 14'h0906;
      end
      16'h0018: begin
        seg = 14'h094c;
      end
      16'h0019: begin
        seg = 14'h0924;
      end
      16'h001a: begin
        seg = 14'h0920;
      end
      16'h001b: begin
        seg = 14'h090f;
      end
      16'h001c: begin
        seg = 14'h0900;
      end
      16'h001d: begin
        seg = 14'h0904;
      end
      16'h001e: begin
        seg = 14'h0301;
      end
      16'h001f: begin
        seg = 14'h034f;
      end
      16'h0020: begin
        seg = 14'h0312;
      end
      16'h0021: begin
        seg = 14'h0306;
      end
      16'h0022: begin
        seg = 14'h034c;
      end
      16'h0023: begin
        seg = 14'h0324;
      end
      16'h0024: begin
        seg = 14'h0320;
      end
      16'h0025: begin
        seg = 14'h030f;
      end
      16'h0026: begin
        seg = 14'h0300;
      end
      16'h0027: begin
        seg = 14'h0304;
      end
      16'h0028: begin
        seg = 14'h2601;
      end
      default: begin
        seg = 14'h0000;
      end
    endcase
  end
endmodule
